// flow-typed signature: 2708102d27d7afca51a181e3f985f9a7
// flow-typed version: <<STUB>>/browserslist_v^1.6.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserslist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserslist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserslist/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserslist/cli.js' {
  declare module.exports: $Exports<'browserslist/cli'>;
}
declare module 'browserslist/index' {
  declare module.exports: $Exports<'browserslist'>;
}
declare module 'browserslist/index.js' {
  declare module.exports: $Exports<'browserslist'>;
}
