// flow-typed signature: 7c293e6b09f3a4185898552a5c9ec35a
// flow-typed version: <<STUB>>/browserslist_v^2.4.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserslist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserslist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserslist/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserslist/cli.js' {
  declare module.exports: $Exports<'browserslist/cli'>;
}
declare module 'browserslist/index' {
  declare module.exports: $Exports<'browserslist'>;
}
declare module 'browserslist/index.js' {
  declare module.exports: $Exports<'browserslist'>;
}
