// flow-typed signature: 32d6d5926a67226106b2415cebc8284e
// flow-typed version: <<STUB>>/caniuse-db_v^1.0.30000741/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
